### ISSUE TITLE
Some things aren't working...

### ISSUE THREAD

**Issue by cowboysdude** [whyjustin/magic-mirror-voice#1]
1.  ./node_modules/.bin/electron-rebuild -v=1.2.8 

Using that returns "No such file or directory"

2.  You put the sample config in your config.js your mirror will load and tell you that you need a valid config.js file...

**Comment by whyjustin** [comment]
> ./node_modules/.bin/electron-rebuild -v=1.2.8
> Using that returns "No such file or directory"

More explanation added to the README via 37d85a4ee1bc44dea059e12ed4ebf6fcfef664e7

> You put the sample config in your config.js your mirror will load and tell you that you need a valid config.js file...

What does your config.js look like?

**Comment by whyjustin** [comment]
> sed -i ‘s/“electron-prebuilt”: “latest”/“electron-prebuilt”: “1.2.8”/g’ package.json
> sed: can’t read package.json: No such file or directory

This needs to be done from the root of the MagicMirror directory. Looking at the instructions [0] it seems you should run `cd ~/MagicMirror/` first.

[0] https://github.com/MichMich/MagicMirror#manual-installation

**Comment by cowboysdude** [comment]
Run from cd ~/MagicMirror
./node_modules/.bin/electron-rebuild -v=1.2.8 
bash: ./node_modules/.bin/electron-rebuild: No such file or directory

Run from cd ~/MagicMirror
sed -i ‘s/“electron-prebuilt”: “latest”/“electron-prebuilt”: “1.2.8”/g’ package.json
sed: -e expression #1, char 1: unknown command: `�'

**Comment by cowboysdude** [comment]
Bad copy on my part!!!   It's downloading

**Comment by cowboysdude** [comment]
Nope good thing I burned an img before I tried to install this... it crashed and wouldn't install... too late now will give it one more shot tomorrow.

**Comment by cowboysdude** [comment]
Get to this point:

sed -i 's/"electron-prebuilt": "latest"/"electron-prebuilt": "1.2.8"/g' package.json
npm install

Within the cd ~/MagicMirror folder and I get an 'can't install node js' error then it stops.

So something is still not working....

**Comment by whyjustin** [comment]
@cowboysdude FWIW

```
cd ~/MagicMirror
git checkout -- package.json
npm install
```

will get you back to normal. Will look more into the problem when I have a chance.

**Comment by cowboysdude** [comment]
Honestly I followed every step... slowly..   Thank you for the 'back to normal' because recopying the img was getting old LOL  

I will try it again... who knows... I've been known to do stupid things...   I mean seriously if you miss even the slightest thing sometimes it can backfire!    So let me do it again tonight and we'll go from there...

**Comment by cowboysdude** [comment]
I'm going to close this issue... I really just don't have the time to mess with it right now.. VERY busy :)  It's a great module and I appreciate your hard work!! Thank you!!!!!
