### ISSUE TITLE
What this will do?

### ISSUE THREAD

**Issue by lucallmon** [whyjustin/magic-mirror-voice#2]
Hi, I'm just curios exactly what this module will do in the end. There is no detailed description in the readme. Also, the installation in the readme leaves much to be desired.

**Comment by whyjustin** [comment]
@lucallmon some detail is available in the Magic Mirror forum [0]. This is a plugin for the Magic Mirror framework that allows you to configure a key phrase which, when uttered, will pass the next audio to Alexa web services. This allows the Magic Mirror to also function as an Alexa enabled device.

[0] https://forum.magicmirror.builders/topic/623/yet-another-voice-module-sphinx-alexa

**Comment by lucallmon** [comment]
So, can you create a more detailed installation instructions? And perhaps a video demo?

**Comment by lucallmon** [comment]
So, have all the issues been resolved? Is it fully functioning? Because I'm waiting to install an Alexa client until I can get one that is (for the most part) bug free. And I would prefer a module for MM2.

**Comment by lucallmon** [comment]
And the Readme file is pretty vague. I'm a NOOB and need something more detailed.

**Comment by whyjustin** [comment]
@lucallmon I appreciate the interest in the project but I do not have any time to dedicate to it. I have stopped using MM2 and instead wrote a custom Magic Mirror implementation so I'm not sure if I will return to this project. Pull Requests welcome although I mainly open sourced it in case anybody would find it helpful. My apologies.
